// Generated by https://quicktype.io

export interface Movie {
  score: number;
  show:  Show;
}

export interface Show {
  id:             number;
  url:            string;
  name:           string;
  type:           'Scripted';
  language:       'Dutch' | 'English' | 'Mongolian';
  genres:         string[];
  status:         'Ended' | 'In Development' | 'Running';
  runtime:        number;
  averageRuntime: number | null;
  premiered:      null | string;
  officialSite:   null | string;
  schedule:       Schedule;
  rating:         Rating;
  weight:         number;
  network:        Network | null;
  webChannel:     Network | null;
  dvdCountry:     null;
  externals:      Externals;
  image:          Image | null;
  summary:        null | string;
  updated:        number;
  _links:         Links;
}

export interface Links {
  self:             Previousepisode;
  previousepisode?: Previousepisode;
}

export interface Previousepisode {
  href: string;
}

export interface Externals {
  tvrage:  number | null;
  thetvdb: number | null;
  imdb:    null | string;
}

export interface Image {
  medium:   string;
  original: string;
}

export interface Network {
  id:      number;
  name:    string;
  country: Country;
}

export interface Country {
  name:     string;
  code:     string;
  timezone: string;
}

export interface Rating {
  average: number | null;
}

export interface Schedule {
  time: string;
  days: string[];
}
